// Pure parts of Toji's Tor integration, shared by the chrome module
// (resource:///modules/toji/lib/tor.sys.mjs, bundled by gecko/build.ts) and the
// Vitest suite. Nothing here touches the network or the filesystem.
//
// Toji never implements onion routing; it runs the real tor and speaks its
// control protocol. Circuit isolation rides on SOCKS authentication: tor's
// IsolateSOCKSAuth keeps streams with different SOCKS username/password pairs on
// different circuits, and Gecko (unlike Chromium) can send SOCKS credentials. So
// each Tor container gets its own credentials, which isolates containers from each
// other on a managed tor *and* on an external one (Tor Browser, a system tor).

/** Where an already-running tor usually listens (system tor, Tor Browser). */
export const EXTERNAL_SOCKS_PORTS = [9050, 9150];

export type TorState = 'off' | 'starting' | 'bootstrapping' | 'ready' | 'error';
export type TorSource = 'managed' | 'external' | null;

export interface TorStatus {
  ready: boolean;
  state: TorState;
  progress: number;
  detail: string;
  source: TorSource;
  /** Tor containers get separate circuits (SOCKS-auth isolation). */
  isolated: boolean;
}

export const OFF_STATUS: TorStatus = {
  ready: false,
  state: 'off',
  progress: 0,
  detail: 'Tor is not running',
  source: null,
  isolated: false
};

/**
 * Applies a patch to the status. `ready` and `isolated` are always derived, never
 * taken from the caller: `ready` gates the kill switch.
 */
export function nextStatus(prev: TorStatus, patch: Partial<TorStatus>): TorStatus {
  const merged = { ...prev, ...patch };
  const ready = merged.state === 'ready';
  return { ...merged, ready, isolated: ready };
}

/** torrc values may contain spaces ("Application Support"); tor accepts C-escaped quotes. */
export function torrcQuote(value: string): string {
  return JSON.stringify(value);
}

export interface TorrcOptions {
  dataDir: string;
  /** Where tor writes the control port it picked ("PORT=127.0.0.1:NNNN"). */
  controlPortFile: string;
  /** tor exits when this process does, so a crashed browser never leaves it behind. */
  ownerPid?: number;
}

/**
 * The managed tor's configuration. Ports are "auto" so tor binds free ones itself
 * (no probe-then-bind race); Toji reads them back over the control port.
 */
export function buildTorrc({ dataDir, controlPortFile, ownerPid }: TorrcOptions): string {
  const lines = [
    '# Generated by Toji. Rewritten on every start.',
    `DataDirectory ${torrcQuote(dataDir)}`,
    'Log notice stdout',
    'ClientOnly 1',
    'AvoidDiskWrites 1',
    'SocksPort auto IsolateSOCKSAuth KeepAliveIsolateSOCKSAuth IsolateDestAddr',
    'ControlPort auto',
    `ControlPortWriteToFile ${torrcQuote(controlPortFile)}`,
    'CookieAuthentication 1',
    ...(ownerPid ? [`__OwningControllerProcess ${ownerPid}`] : [])
  ];
  return lines.join('\n') + '\n';
}

/** Bootstrap progress out of a tor notice line, or null if it isn't one. */
export function parseBootstrap(line: string): { progress: number; detail: string } | null {
  const match = /Bootstrapped (\d+)%(?:\s*\(([^)]*)\))?(?::\s*(.*))?/.exec(line);
  if (!match) return null;
  const progress = Number(match[1]);
  const detail = (match[3] || match[2] || '').trim();
  return { progress, detail: detail || `Bootstrapping ${progress}%` };
}

/** The port out of tor's ControlPortWriteToFile ("PORT=127.0.0.1:9151"). */
export function parseControlPortFile(text: string): number | null {
  const match = /PORT=127\.0\.0\.1:(\d+)/.exec(text);
  return match ? Number(match[1]) : null;
}

export interface ControlReply {
  /** Status code of the final line (250 = OK). */
  code: number;
  /** Every line's text after the code and separator. */
  lines: string[];
}

/**
 * Splits a control-port transcript into complete replies. A reply ends at a line
 * whose fourth character is a space ("250 OK"); "250-" continues it, and "250+"
 * opens a data block of raw lines ending with a lone "." (leading dots doubled).
 * Data-block lines are appended to the reply's lines after the "250+" line's text.
 * Returns the complete replies and whatever trailing text is still incomplete.
 */
export function parseReplies(buffer: string): { replies: ControlReply[]; rest: string } {
  const replies: ControlReply[] = [];
  let pos = 0;
  let start = 0;
  let lines: string[] = [];
  let inData = false;
  for (;;) {
    const nl = buffer.indexOf('\r\n', pos);
    if (nl < 0) break;
    const line = buffer.slice(pos, nl);
    pos = nl + 2;
    if (inData) {
      if (line === '.') inData = false;
      else lines.push(line.startsWith('..') ? line.slice(1) : line);
      continue;
    }
    if (line.length < 4) continue;
    lines.push(line.slice(4));
    if (line[3] === '+') {
      inData = true;
    } else if (line[3] === ' ') {
      replies.push({ code: Number(line.slice(0, 3)), lines });
      lines = [];
      start = pos;
    }
  }
  // Anything after the last complete reply waits for the next chunk.
  return { replies, rest: buffer.slice(start) };
}

/** The first SOCKS listener out of `GETINFO net/listeners/socks`. */
export function parseSocksListener(reply: ControlReply): number | null {
  for (const line of reply.lines) {
    const match = /net\/listeners\/socks=.*?"127\.0\.0\.1:(\d+)"/.exec(line) || /net\/listeners\/socks=.*?127\.0\.0\.1:(\d+)/.exec(line);
    if (match) return Number(match[1]);
  }
  return null;
}

/** Hex-encodes the control cookie for AUTHENTICATE. */
export function cookieHex(bytes: Uint8Array): string {
  return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
}

/**
 * SOCKS credentials for a container. The username names the container; the password
 * carries a per-launch nonce and a generation the container bumps for a new circuit.
 * Different credentials → different circuits (IsolateSOCKSAuth).
 */
export function socksCredentials(containerId: string, nonce: string, generation = 0): { username: string; password: string } {
  return { username: `toji:${containerId}`, password: `${nonce}:${generation}` };
}

/** Candidate tor binaries, most specific first. */
export function torBinaryCandidates(opts: { bundled?: string; env?: string }): string[] {
  return [opts.bundled, opts.env, '/opt/homebrew/bin/tor', '/usr/local/bin/tor', '/usr/bin/tor', '/usr/sbin/tor'].filter(
    (p): p is string => Boolean(p)
  );
}
