// Tor process management and per-container circuit isolation.
//
// Toji never implements onion routing itself — that would be reckless. It drives the
// real Tor client and speaks its control protocol.
//
// Circuit isolation: Tor keeps streams arriving on different SocksPorts on separate
// circuits, and an explicit SessionGroup per port makes that guarantee unconditional.
// So a managed Tor gets a small pool of SocksPorts and each Tor container is assigned
// one, which is what stops two containers from sharing an exit and being trivially
// correlated by it.
//
// An external Tor (Tor Browser, `brew services start tor`) can still be used, but it
// offers a single SOCKS port. Chromium cannot send SOCKS credentials, so per-container
// isolation is unavailable in that mode and the UI says so rather than implying an
// isolation that isn't there.

const { spawn } = require('node:child_process');
const fs = require('node:fs');
const net = require('node:net');
const path = require('node:path');

/** Ports for the managed instance. Deliberately clear of system Tor (9050) and Tor Browser (9150). */
const SOCKS_BASE = 9070;
const SOCKS_POOL_SIZE = 6;
const CONTROL_BASE = 9069;

/** Where an already-running Tor usually listens. */
const EXTERNAL_SOCKS_PORTS = [9050, 9150];

const BINARY_CANDIDATES = [
  process.env.TOJI_TOR_BINARY,
  '/opt/homebrew/bin/tor',
  '/usr/local/bin/tor',
  '/usr/bin/tor',
  '/usr/sbin/tor'
].filter(Boolean);

/** Locate a tor binary, including one bundled inside the packaged app. */
function findTorBinary(resourcesPath) {
  const candidates = [...BINARY_CANDIDATES];
  if (resourcesPath) candidates.unshift(path.join(resourcesPath, 'tor', 'tor'));
  return candidates.find((candidate) => {
    try {
      fs.accessSync(candidate, fs.constants.X_OK);
      return true;
    } catch {
      return false;
    }
  }) ?? null;
}

/** True when something is already listening on `port` (i.e. an external Tor). */
function probePort(port, host = '127.0.0.1', timeoutMs = 400) {
  return new Promise((resolve) => {
    const socket = new net.Socket();
    const done = (result) => {
      socket.destroy();
      resolve(result);
    };
    socket.setTimeout(timeoutMs);
    socket.once('connect', () => done(true));
    socket.once('timeout', () => done(false));
    socket.once('error', () => done(false));
    socket.connect(port, host);
  });
}

/** First of the usual external Tor ports that is actually accepting connections. */
async function findExternalSocks() {
  for (const port of EXTERNAL_SOCKS_PORTS) {
    if (await probePort(port)) return port;
  }
  return null;
}

/** Whether we can bind `port` ourselves (i.e. it is free for the managed instance). */
function portIsFree(port) {
  return new Promise((resolve) => {
    const server = net.createServer();
    server.once('error', () => resolve(false));
    server.once('listening', () => server.close(() => resolve(true)));
    server.listen(port, '127.0.0.1');
  });
}

/** Claim `count` consecutive-ish free ports starting the search at `base`. */
async function allocatePorts(base, count) {
  const ports = [];
  for (let port = base; port < base + 200 && ports.length < count; port += 1) {
    if (await portIsFree(port)) ports.push(port);
  }
  if (ports.length < count) throw new Error(`could not find ${count} free ports near ${base}`);
  return ports;
}

/**
 * Build a torrc. One SocksPort per pool slot, each in its own SessionGroup so Tor is
 * explicitly told to keep their circuits apart.
 */
function buildTorrc({ dataDir, socksPorts, controlPort }) {
  const lines = [
    '# Generated by Toji. Edits are overwritten on every start.',
    `DataDirectory ${dataDir}`,
    'Log notice stdout',
    'ClientOnly 1',
    // No SOCKS auth from Chromium, so isolation rides entirely on the port/session group.
    ...socksPorts.map((port, index) => `SocksPort 127.0.0.1:${port} SessionGroup=${index + 1} IsolateDestAddr`),
    `ControlPort 127.0.0.1:${controlPort}`,
    'CookieAuthentication 1'
  ];
  return lines.join('\n') + '\n';
}

/** Pull bootstrap progress out of a Tor notice line, or null if it isn't one. */
function parseBootstrap(line) {
  const match = /Bootstrapped (\d+)%(?:\s*\(([^)]*)\))?(?::\s*(.*))?/.exec(line);
  if (!match) return null;
  const progress = Number(match[1]);
  const detail = (match[3] || match[2] || '').trim();
  return { progress, detail: detail || `Bootstrapping ${progress}%` };
}

/** Frame a control-port conversation: authenticate with the cookie, then run commands. */
function controlCommands(cookieHex, commands) {
  return [`AUTHENTICATE ${cookieHex}`, ...commands, 'QUIT'].join('\r\n') + '\r\n';
}

class TorController {
  constructor({ dataDir, resourcesPath, log }) {
    this.dataDir = dataDir;
    this.resourcesPath = resourcesPath;
    this.log = log || (() => {});
    this.process = null;
    this.socksPorts = [];
    this.controlPort = null;
    this.externalPort = null;
    /** containerId → SocksPort, so a container keeps the same circuits for its lifetime. */
    this.assignments = new Map();
    this.listeners = new Set();
    this.status = { ready: false, state: 'off', progress: 0, detail: 'Tor is not running', source: null, isolated: false };
  }

  onStatus(listener) {
    this.listeners.add(listener);
    return () => this.listeners.delete(listener);
  }

  setStatus(patch) {
    this.status = { ...this.status, ...patch };
    // Derived, never taken from the caller: `ready` gates the kill switch, and
    // `isolated` tells the UI whether containers really do get separate circuits.
    this.status.ready = this.status.state === 'ready';
    this.status.isolated = Boolean(this.status.ready && !this.externalPort && this.socksPorts.length > 1);
    for (const listener of this.listeners) {
      try {
        listener(this.status);
      } catch {
        /* a dead window must not break the others */
      }
    }
  }

  isReady() {
    return this.status.ready;
  }

  /**
   * The SOCKS port a container's traffic goes through. Managed Tor hands out a distinct
   * port per container (round-robin once the pool is exhausted); an external Tor has
   * only one, so every container shares it.
   */
  socksPortFor(containerId) {
    if (!this.status.ready) return null;
    if (this.externalPort) return this.externalPort;
    if (!this.socksPorts.length) return null;
    if (!this.assignments.has(containerId)) {
      this.assignments.set(containerId, this.socksPorts[this.assignments.size % this.socksPorts.length]);
    }
    return this.assignments.get(containerId);
  }

  /** True when each Tor container gets its own circuits (managed instance only). */
  get isolated() {
    return this.status.isolated;
  }

  async start() {
    if (this.process || this.status.state === 'starting' || this.status.state === 'bootstrapping') return this.status;
    this.setStatus({ state: 'starting', progress: 0, detail: 'Starting Tor' });

    const binary = findTorBinary(this.resourcesPath);
    if (!binary) {
      // No binary of our own — fall back to an already-running Tor if there is one.
      const external = await findExternalSocks();
      if (external) {
        this.externalPort = external;
        this.setStatus({ state: 'ready', progress: 100, detail: `Using Tor already running on port ${external}`, source: 'external' });
        return this.status;
      }
      this.setStatus({
        state: 'error',
        progress: 0,
        detail: 'No Tor found. Install it (macOS: brew install tor) or start Tor Browser, then try again.',
        source: null
      });
      return this.status;
    }

    try {
      fs.mkdirSync(this.dataDir, { recursive: true, mode: 0o700 });
      this.socksPorts = await allocatePorts(SOCKS_BASE, SOCKS_POOL_SIZE);
      [this.controlPort] = await allocatePorts(CONTROL_BASE, 1);
      const torrcPath = path.join(this.dataDir, 'torrc');
      fs.writeFileSync(torrcPath, buildTorrc({ dataDir: this.dataDir, socksPorts: this.socksPorts, controlPort: this.controlPort }));

      this.setStatus({ state: 'bootstrapping', progress: 0, detail: 'Connecting to the Tor network', source: 'managed' });
      this.process = spawn(binary, ['-f', torrcPath], { stdio: ['ignore', 'pipe', 'pipe'] });

      this.process.stdout.on('data', (chunk) => {
        for (const line of String(chunk).split('\n')) {
          if (!line.trim()) continue;
          this.log(`[tor] ${line.trim()}`);
          const bootstrap = parseBootstrap(line);
          if (!bootstrap) continue;
          if (bootstrap.progress >= 100) this.setStatus({ state: 'ready', progress: 100, detail: 'Connected to the Tor network' });
          else this.setStatus({ state: 'bootstrapping', progress: bootstrap.progress, detail: bootstrap.detail });
        }
      });
      this.process.stderr.on('data', (chunk) => this.log(`[tor:err] ${String(chunk).trim()}`));
      this.process.on('error', (error) => {
        this.process = null;
        this.setStatus({ state: 'error', progress: 0, detail: `Tor failed to start: ${error.message}` });
      });
      this.process.on('exit', (code) => {
        this.process = null;
        this.assignments.clear();
        // Anything other than a stop we asked for is a failure the user must see: their
        // Tor containers just went offline.
        if (this.status.state !== 'off') this.setStatus({ state: 'error', progress: 0, detail: `Tor exited (code ${code ?? 'unknown'})` });
      });
    } catch (error) {
      this.setStatus({ state: 'error', progress: 0, detail: `Tor failed to start: ${error.message}` });
    }
    return this.status;
  }

  stop() {
    this.setStatus({ state: 'off', progress: 0, detail: 'Tor is not running', source: null });
    this.assignments.clear();
    this.externalPort = null;
    if (this.process) {
      this.process.kill();
      this.process = null;
    }
    return this.status;
  }

  /**
   * Ask Tor for fresh circuits (NEWNYM). This is global to the Tor instance, so every
   * container gets new circuits at once — Tor exposes no per-port signal.
   */
  async newCircuit() {
    if (!this.controlPort) return false;
    let cookieHex;
    try {
      cookieHex = fs.readFileSync(path.join(this.dataDir, 'control_auth_cookie')).toString('hex');
    } catch (error) {
      this.log(`[tor] control cookie unreadable: ${error.message}`);
      return false;
    }
    return new Promise((resolve) => {
      const socket = net.connect(this.controlPort, '127.0.0.1');
      let response = '';
      const finish = (ok) => {
        socket.destroy();
        resolve(ok);
      };
      socket.setTimeout(3000);
      socket.once('timeout', () => finish(false));
      socket.once('error', () => finish(false));
      socket.on('data', (chunk) => {
        response += chunk.toString();
        // Two 250s: one for AUTHENTICATE, one for SIGNAL NEWNYM.
        if ((response.match(/^250/gm) || []).length >= 2) finish(true);
        if (/^5\d\d/m.test(response)) finish(false);
      });
      socket.once('connect', () => socket.write(controlCommands(cookieHex, ['SIGNAL NEWNYM'])));
    });
  }
}

module.exports = {
  TorController,
  SOCKS_BASE,
  SOCKS_POOL_SIZE,
  EXTERNAL_SOCKS_PORTS,
  findTorBinary,
  findExternalSocks,
  probePort,
  portIsFree,
  allocatePorts,
  buildTorrc,
  parseBootstrap,
  controlCommands
};
